# permissions for end users to edit conductors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: idea3project
    app.kubernetes.io/managed-by: kustomize
  name: conductor-editor-role
rules:
- apiGroups:
  - apps.haojiang.cn
  resources:
  - conductors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.haojiang.cn
  resources:
  - conductors/status
  verbs:
  - get
