apiVersion: apps.haojiang.cn/v1
kind: Conductor
metadata:
  labels:
    app.kubernetes.io/name: idea3project
    app.kubernetes.io/managed-by: kustomize
  name: conductor-sample
spec:
  # TODO(user): Add fields here
